line_follower_node: # This must match the name of the node in the launch file
  ros__parameters:
    kp: 0.008
    kd: 0.001
    dt: 0.1
    image_height: 240
    image_width: 320
    canny_sigma: 0.05
    line_timeout_seconds: 1.0
    linear_speed: 0.09
    angular_speed_limit: 0.8
    linear_speed_error_factor: 0.01
    min_line_angle_deg: 25.0
    max_line_angle_deg: 155.0
    hough_threshold: 30
    hough_min_line_length: 15
    hough_max_line_gap: 13
    roi_bottom_width_offset: 50
    clahe_clip_limit: 2.0
    clahe_tile_grid_size: [8, 8] # YAML list syntax
    gaussian_blur_kernel_size: [11, 11] # YAML list syntax
    gaussian_blur_sigma_x: 2.0